version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - 9070:80
    volumes:
      - /mnt/hdd:/srv
      - ./filebrowser.db:/database/filebrowser.db
      - ./filebrowser.json:/.filebrowser.json
    restart: unless-stopped
