services:

  invidious:
    image: quay.io/invidious/invidious:latest
    container_name: invidious
    # image: quay.io/invidious/invidious:latest-arm64 # ARM64/AArch64 devices
    restart: unless-stopped
    ports:
      - "3000:3000"
    labels:
      tsdproxy.enable: "true"
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: $VISITOR_DATA
        po_token: $PO_TOKEN
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: $HMAC_KEY
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:latest
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

  # materialious:
  #   container_name: materialious
  #   image: wardpearce/materialious:latest
  #   restart: unless-stopped
  #   ports:
  #     - 3001:80
  #   environment:
  #     # No trailing backslashes!
  #     # URL to your proxied Invidious instance
  #     VITE_DEFAULT_INVIDIOUS_INSTANCE: "https://invidious.tail08f17.ts.net"
  #   labels:
  #     tsdproxy.enable: "true"
