services:
  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - './data:/data'
      - './:/config'
    logging:
      driver: json-file
      options:
        max-size: 10m
    env_file: .env
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn