services:
  code-container:
    image: code-container:latest
    build:
      context: .
    ports:
      - "5173:5173"
      - "3000:3000"
    volumes:
      - ./workspaces:/home/vscode/projects
      - /home/gus/.ssh/id_ed25519:/home/vscode/.ssh/id_ed25519:ro
    restart: unless-stopped
    container_name: code-container
    command: sleep infinity
