services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable
    ports:
      - 8971:8971
    volumes:
      - ./config:/config
      - /mnt/hdd/frigate:/media
    shm_size: 2gb
    privileged: true

