services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 0:0 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "https://navidrome.tail08f17.ts.net"
    volumes:
      - ./data:/data
      - /mnt/bendo4/SHARE/media/music:/music:ro
    labels:
      tsdproxy.enable: "true"
