
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    command:
      --cert
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/MST
      - PASSWORD=gus #optional
      - SUDO_PASSWORD=gus #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./data:/home/coder
    ports:
      - 8082:8080
    restart: unless-stopped
