services:
  scrutiny:
    container_name: scrutiny-mj
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "8092:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda:/dev/sda
      #- /dev/sdb:/dev/sdb
      - /dev/nvme0n1:/dev/nvme0n1
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
