services:
  tileD:
    container_name: tileD
    image: gusvendegna/tiled:latest
    ports:
      - 9080:5000
    env_file:
      - .env
    volumes:
      - ./data/tileD.db:/python_docker/tileD.db
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:5000/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    