name: Docker Compose Restart Policy Check

on:
  push:
    branches: [main] # run on pushes to main branch only

jobs:
  check-restart-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and check all Docker Compose files
        env:
          DOCKER_FILES_DIR: ${{ github.workspace }}/docker/
        run: |
          find "${DOCKER_FILES_DIR}" -name docker-compose.yml | while read -r file; do
            if ! grep -qE "(restart\s*:\s*(always|unless-stopped))" "$file"; then
              echo "Error: Restart policy not set in $file"
              exit 1
            fi
          done

      - name: Check if all files have correct restart policy
        run: |
          if [ $? -ne 0 ]; then
            echo "One or more Docker Compose files do not have the correct restart policy. Aborting."
            exit 1
          fi